#!/usr/bin/env bun
import {
  constants,
  copyFileSync,
  linkSync,
  lstatSync,
  mkdirSync,
  readdirSync,
  realpathSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";
import { parseArgs } from "node:util";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import {
  loadConversionSource,
  type ConversionReport,
  type ConversionSource,
} from "./conversion-source";

export type ConvertOptions = {
  out?: string;
  sourceRoot?: string;
  include?: string[];
  dryRun?: boolean;
};

export type ConvertResult = {
  exitCode: 0 | 1 | 2;
  report: ConversionReport & {
    output: { entrypoint: string | null; resources: string[]; excludedResources: string[] };
  };
};

type Resource = { source: string; relative: string };

function within(root: string, target: string): boolean {
  const relative = path.relative(root, target);
  return relative === "" || (!relative.startsWith(`..${path.sep}`) && relative !== ".." && !path.isAbsolute(relative));
}

const EXCLUDED_NAMES: Record<string, true> = {
  ".git": true, ".hg": true, ".svn": true, node_modules: true,
  ".venv": true, __pycache__: true, ".cache": true, ".pi": true,
  ".omp": true, ".claude": true,
};

function excludedName(name: string): boolean {
  return EXCLUDED_NAMES[name.toLowerCase()] === true
    || /^(?:\.env(?:\..*)?|credentials(?:\..*)?|id_rsa|id_ed25519)$/i.test(name)
    || /\.(?:pem|key|p12|pfx)$/i.test(name)
    || /^(?:package(?:-lock)?\.json|bun\.lockb?|yarn\.lock|pnpm-lock\.yaml)$/i.test(name);
}

function collectResources(source: ConversionSource, includes: string[]): { files: Resource[]; excluded: string[] } {
  const files = new Map<string, Resource>();
  const excluded = new Set<string>();
  const declarations = new Set(source.declarationFiles.map(file => path.resolve(file)));
  const realRoot = realpathSync(source.root);
  const visit = (file: string): void => {
    const relative = path.relative(source.root, file).split(path.sep).join("/");
    if (!within(source.root, file)) throw new Error("A resource path escapes the source root");
    if (excludedName(path.basename(file)) || declarations.has(file)) {
      excluded.add(relative);
      return;
    }
    const stat = lstatSync(file);
    if (stat.isSymbolicLink()) {
      source.report.diagnostics.push({ level: "unsupported", file: relative, message: "Resource symlinks require explicit resolution before conversion" });
      return;
    }
    if (!within(realRoot, realpathSync(file))) throw new Error("A resource resolves outside the source root");
    if (stat.isDirectory()) {
      for (const name of readdirSync(file).sort()) visit(path.join(file, name));
    } else if (stat.isFile()) {
      files.set(relative, { source: file, relative });
    } else {
      source.report.diagnostics.push({ level: "unsupported", file: relative, message: "Only regular resource files can be copied" });
    }
  };

  if (source.kind === "plugin") {
    for (const name of readdirSync(source.root).sort()) visit(path.join(source.root, name));
  }
  for (const include of includes) {
    if (path.isAbsolute(include)) throw new Error("--include paths must be relative to --source-root");
    const file = path.resolve(source.root, include);
    if (!within(source.root, file)) throw new Error("An --include path escapes the source root");
    // Check every component, including excluded ancestors and symlink parents.
    let component = source.root;
    for (const name of path.relative(source.root, file).split(path.sep).filter(Boolean)) {
      component = path.join(component, name);
      if (excludedName(name) || lstatSync(component).isSymbolicLink()) {
        throw new Error("--include cannot select excluded files or traverse symlinks");
      }
    }
    visit(file);
  }
  return {
    files: [...files.values()].sort((a, b) => a.relative < b.relative ? -1 : a.relative > b.relative ? 1 : 0),
    excluded: [...excluded].sort(),
  };
}

function generatedEntrypoint(source: ConversionSource): string {
  const definition = JSON.stringify(source.settings, null, 2);
  const dataId = `${source.name.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64) || "hooks"}-${createHash("sha256").update(definition).digest("hex").slice(0, 12)}`;
  return `// Generated by omp-hooks-plus's one-shot converter. Load this file in OMP.
// Disable overlapping original hooks before loading it. External script dependencies still apply.
import { mkdirSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { registerHooks } from "./lib/adapter.js";

const definition = ${definition};
const pluginRoot = join(dirname(fileURLToPath(import.meta.url)), "resources");
const pluginData = join(homedir(), ".omp", "hook-data", ${JSON.stringify(dataId)});

export default function (pi) {
  let cachedCwd;
  let settings;
  registerHooks(pi, async (ctx) => {
    if (definition.disableAllHooks || !definition.hooks) return undefined;
    if (cachedCwd !== ctx.cwd) {
      mkdirSync(pluginData, { recursive: true });
      settings = {
        hooks: Object.fromEntries(Object.entries(definition.hooks).map(([event, groups]) => [
          event,
          groups.map(group => ({
            ...group,
            hooks: group.hooks.map(hook => ({
              ...hook,
              env: {
                ...hook.env,
                CLAUDE_PLUGIN_ROOT: pluginRoot,
                CLAUDE_PLUGIN_DATA: pluginData,
                CLAUDE_PROJECT_DIR: ctx.cwd,
              },
            })),
          })),
        ])),
      };
      cachedCwd = ctx.cwd;
    }
    return settings;
  });
}
`;
}

function bundledAdapter(): Uint8Array {
  if (!process.versions.bun) throw new Error("Run the converter with Bun");
  // Compile only trusted repository code, never plugin modules or build plugins.
  return execFileSync(process.execPath, [
    "build", path.join(path.dirname(fileURLToPath(import.meta.url)), "adapter.ts"),
    "--target=bun", "--format=esm", "--minify", "--packages=external",
  ], { maxBuffer: 16 * 1024 * 1024, stdio: ["ignore", "pipe", "pipe"] });
}

function destinationPath(out: string, sourceRoot: string): string {
  const requested = path.resolve(out);
  if (within(sourceRoot, requested)) throw new Error("Output must be outside the source root");
  const parent = realpathSync(path.dirname(requested));
  const destination = path.join(parent, path.basename(requested));
  if (within(realpathSync(sourceRoot), destination)) throw new Error("Output resolves inside the source root");
  try {
    lstatSync(destination);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return destination;
    throw error;
  }
  throw new Error("Output already exists; choose a new directory");
}

/** Analyze explicitly supplied source and optionally write new OMP hook files. Never executes source hooks. */
export async function convertHooks(input: string, options: ConvertOptions = {}): Promise<ConvertResult> {
  if (!options.dryRun && !options.out) throw new Error("--out is required unless --dry-run is used");
  const source = await loadConversionSource(input, { sourceRoot: options.sourceRoot });
  const destination = options.out ? destinationPath(options.out, source.root) : undefined;
  const resources = collectResources(source, options.include ?? []);
  for (const groups of Object.values(source.settings.hooks ?? {})) {
    for (const group of groups ?? []) {
      for (const hook of group.hooks ?? []) {
        if (hook.command.includes(source.root) || hook.args?.some(argument => argument.includes(source.root))) {
          source.report.diagnostics.push({ level: "unsupported", message: "A command embeds the original absolute source root; review its resource references before conversion" });
        }
      }
    }
  }
  source.report.diagnostics.push({ level: "info", message: "Commands retain their shell and active-project working directory. External executables, services and script dependencies remain required; arbitrary script dependency closure is not verified." });
  if (source.kind === "file") {
    source.report.diagnostics.push({ level: "info", message: "File inputs do not copy the containing project. Use --source-root and --include for resources referenced through CLAUDE_PLUGIN_ROOT; ordinary relative commands remain project-relative." });
  }
  const exitCode = source.report.diagnostics.some(item => item.level === "error") ? 1
    : source.report.diagnostics.some(item => item.level === "unsupported") ? 2 : 0;
  const report: ConvertResult["report"] = {
    ...source.report,
    output: {
      entrypoint: exitCode === 0 ? "index.ts" : null,
      resources: exitCode === 0 ? resources.files.map(file => file.relative) : [],
      excludedResources: resources.excluded,
    },
  };
  if (options.dryRun || exitCode === 1) return { exitCode, report };

  // Build before touching the destination. mkdir is exclusive across converter invocations.
  const adapter = exitCode === 0 ? bundledAdapter() : undefined;
  mkdirSync(destination!);
  try {
    if (adapter) {
      mkdirSync(path.join(destination!, "lib"));
      mkdirSync(path.join(destination!, "resources"));
      writeFileSync(path.join(destination!, "lib", "adapter.js"), adapter, { flag: "wx" });
      copyFileSync(fileURLToPath(new URL("../LICENSE", import.meta.url)), path.join(destination!, "LICENSE"), constants.COPYFILE_EXCL);
      for (const resource of resources.files) {
        const target = path.join(destination!, "resources", resource.relative);
        mkdirSync(path.dirname(target), { recursive: true });
        copyFileSync(resource.source, target, constants.COPYFILE_EXCL);
      }
    }
    writeFileSync(path.join(destination!, "conversion-report.json"), `${JSON.stringify(report, null, 2)}\n`, { flag: "wx" });
    if (adapter) {
      // Publish the discoverable entrypoint last, in one no-replace filesystem operation.
      const temporary = path.join(destination!, ".entrypoint.tmp");
      writeFileSync(temporary, generatedEntrypoint(source), { flag: "wx" });
      linkSync(temporary, path.join(destination!, "index.ts"));
      unlinkSync(temporary);
    }
  } catch (error) {
    try { rmSync(destination!, { recursive: true, force: true }); }
    catch { throw new Error(`Conversion failed; temporary output could not be removed: ${destination}`, { cause: error }); }
    throw error;
  }
  return { exitCode, report };
}

function printReport(result: ConvertResult, json: boolean, dryRun: boolean): void {
  if (json) {
    console.log(JSON.stringify(result.report, null, 2));
    return;
  }
  for (const hook of result.report.hooks) console.log(`${hook.status}: ${hook.file}${hook.pointer} (${hook.event})`);
  for (const diagnostic of result.report.diagnostics) {
    console.log(`${diagnostic.level}: ${diagnostic.file ?? ""}${diagnostic.pointer ?? ""}${diagnostic.file ? ": " : ""}${diagnostic.message}`);
  }
  if (result.report.output.excludedResources.length) console.log(`Excluded resources: ${result.report.output.excludedResources.join(", ")}`);
  console.log(result.exitCode === 0 ? dryRun ? "Supported hook inventory complete. Dry run: no output was written." : "Supported hook conversion complete. Load index.ts only where intended; disable overlapping originals."
    : result.exitCode === 2 ? "Unsupported declarations remain. No runnable entrypoint was emitted."
    : "Invalid hook declarations. No output was written.");
}

if (import.meta.main) {
  try {
    const { values, positionals } = parseArgs({
      args: process.argv.slice(2),
      allowPositionals: true,
      strict: true,
      options: {
        out: { type: "string" },
        "source-root": { type: "string" },
        include: { type: "string", multiple: true },
        "dry-run": { type: "boolean", default: false },
        json: { type: "boolean", default: false },
        help: { type: "boolean", short: "h", default: false },
      },
    });
    if (values.help) {
      console.log("Usage: bun run convert <plugin-directory|hooks.json|settings.json> --out <new-directory> [--source-root <directory>] [--include <relative-resource>] [--dry-run] [--json]");
    } else {
      if (positionals.length !== 1) throw new Error("Supply exactly one Claude plugin directory or hooks/settings JSON file");
      const result = await convertHooks(positionals[0], {
        out: values.out,
        sourceRoot: values["source-root"],
        include: values.include,
        dryRun: values["dry-run"],
      });
      printReport(result, values.json!, values["dry-run"]!);
      process.exitCode = result.exitCode;
    }
  } catch (error) {
    console.error(`Conversion failed: ${error instanceof Error ? error.message : String(error)}`);
    process.exitCode = 1;
  }
}
